### ISSUE TITLE
No disk space available

### ISSUE THREAD

**Issue by lhimo** [matthuisman/pinn-os#1]
After using the http://noobs.matthuisman.nz/ applet to create a recovery.cmdline I get a "No more disk available" when clicking on the Install button on Pinn boot.. I used a formatted 16GB SD card with the attached recovery.cmdline
[recovery (2).zip](https://github.com/matthuisman/pinn-os/files/1873383/recovery.2.zip)

**Comment by matthuisman** [comment]
Thanks for providing the cmdline.
I see the issue and will try to fix shortly :)
I'll re-post when it's done
