### ISSUE TITLE
partitions.json has wrong size info

### ISSUE THREAD

**Issue by nuwonda** [matthuisman/pinn-os#10]
Hi, I left an issue in https://github.com/procount/pinn-os/issues/8 before I noticed it should go here. Please see there or here: https://github.com/nuwonda/pinn-os-batocera

main issue is that the nominal partition size has to be min. 3GB otherwise can't update unless user repartitions.

other issues are minor and noted in my readme, I just wanted to add RPI4 builds. Cheers!

**Comment by matthuisman** [comment]
ill reply on pinn isue :)
