### ISSUE TITLE
Update batocera

### ISSUE THREAD

**Issue by netsba** [matthuisman/pinn-os#15]
Please update batocera to version 5.27. I use it every day and if I do it directly since batocera, I have a black screen

**Comment by matthuisman** [comment]
@netsba 
i've checked my OS's and batocera automatically gets latest version when installed via PINN

**Comment by netsba** [comment]
Okay, maybe the problem is coming from my screen.
I Will try a clean installation.

**Comment by netsba** [comment]
Problem solved, I just did the update via pinn and I have 5.27. Thank you and sorry for the inconvenience
