### ISSUE TITLE
PINN/Volumio SSD boot

### ISSUE THREAD

**Issue by etnalta** [matthuisman/pinn-os#17]
Hi,

It seems impossible to install Volumio/PINN when booting from USBkey/SSD?
Volumio does not appears in the OSes list.

I tried to add Volumio in /os, no way, PINN doesn’t list Volumio.
Any idea?

**Comment by matthuisman** [comment]
pretty sure when I tried, Volumio didn't support USB booting

**Comment by etnalta** [comment]
Thanks.

Bad news, we are stuck to the reliability of SDCard

**Comment by matthuisman** [comment]
i have just enabled Volumio to allow to install to USB.
Probably won't work - but good luck!

**Comment by etnalta** [comment]
Thanks.I made a test "out of the box", as you expected, it doesn't work. No time and essentially no skills on my side to go further. Right now it works great from SD.Thanks for your work.Le 26 nov. 2020 22:56, Matt Huisman <notifications@github.com> a écrit :
i have just enabled Volumio to allow to install to USB.
Probably won't work - but good luck!
