### ISSUE TITLE
Raspberry Pi 3 Model A compatibility

### ISSUE THREAD

**Issue by nsilveri** [matthuisman/pinn-os#18]
Hi, can you add the compatibility for Model A+ in some OSes? 
I need to install Batocera on my RPi 3 A+ but i see you don't put it as compatible model 

"supported_models": [
                "Pi Model",
                "Pi 2",
                "Pi Zero",
                "Pi Compute Module Rev",
                "Pi Compute Module 3",
                "Pi 3 Model B Rev",
                "Pi 3 Model A Plus Rev", # i think this must be add here, right?
                "Pi 3 Model B Plus Rev"
            ],

**Comment by matthuisman** [comment]
done :)

**Comment by nsilveri** [comment]
Thanks! ;)
