### ISSUE TITLE
Volumio OTA updates

### ISSUE THREAD

**Issue by alfieoriginal** [matthuisman/pinn-os#19]
Hello Volumio OTA update to 2.853 rev (latest) doesn't work. Is there any way to get updates properly accomplished? Thank you in advance.

**Comment by matthuisman** [comment]
Volumio would need to make there OS pinn / noobs friendly for that.

**Comment by matthuisman** [comment]
i have fixed the init so it now works with OTA updates.
You'll need to re-install via PINN, but going forward - OTA should work
