### ISSUE TITLE
Volumio Checksum Error

### ISSUE THREAD

**Issue by alfieoriginal** [matthuisman/pinn-os#20]
![IMG_20201209_140946](https://user-images.githubusercontent.com/14834607/101635167-e382c380-3a29-11eb-9b2f-21c9e7862bd7.jpg)
i have fixed the init so it now works with OTA updates.
You'll need to re-install via PINN, but going forward - OTA should work

_Originally posted by @matthuisman in https://github.com/matthuisman/pinn-os/issues/19#issuecomment-741510410_

Hello again, Can't re-install Volumio, there is a checksum error. Thanks in advance.

**Comment by matthuisman** [comment]
should be good now! please try.
I've kept it back at 2.779 so you can try the OTA and make sure it works
