### ISSUE TITLE
Volumio does not upgrade correctly. eth0 does not exist anymore.

### ISSUE THREAD

**Issue by alfieoriginal** [matthuisman/pinn-os#22]
Hello after updating to new Volumio 3 (3.165 or newer) wired network is not working.

Trying to change network config shows:

"Error: Command failed: /usr/bin/sudo /bin/ip addr flush dev eth0 && /usr/bin/sudo /sbin/ifconfig eth0 down && /usr/bin/sudo /sbin/ifconfig eth0 up Device "eth0" does not exist"

RPI3
Pinn is updated
Wireless is working.

I've installed the Volumio 3 to a fresh SD card and does not exhibit the same problem. I can see and config the wired network. This issue appears only when Volumio is upgraded on Pinn.

Could you check it or give me a hint?
Thank you in advance

**Comment by Olivastro12** [comment]
I enter and support the question posed. In fact, I do not find information on the object. Is the version of Volumio for Pinn actually upgradeable using Volumio or do you have to wait for the file to be recompiled with which you install from Pinn Volumio as in the case of version 2.82 currently? Thanks if you want to clarify this too!

**Comment by matthuisman** [comment]
i will reply over here:
https://github.com/procount/pinn/issues/596
