### ISSUE TITLE
Add/update to 22.04 LTS versions of pinn OS

### ISSUE THREAD

**Issue by MrSilk314** [matthuisman/pinn-os#23]
20.04 LTS versions are available
https://ubuntu-mate.org/download/armhf/jammy/
https://ubuntu-mate.org/download/arm64/jammy/

https://manjaro.org/download/ has 6 desktop (Gnome, Plasma, Mate, Sway, Xfce & minimal) versions
https://github.com/manjaro-arm/rpi4-images/releases/download/22.06/Manjaro-ARM-mate-rpi4-22.06.img.xz.torrent

**Comment by matthuisman** [comment]
I don't maintain those ones for pinn. Your best asking in the pinn forum or on their GitHub
