### ISSUE TITLE
Rasplex needs update

### ISSUE THREAD

**Issue by ktilson** [matthuisman/pinn-os#24]
Rasplex was updated to version 1.8.0b which fixes a certificate issue.  Can this image please be updated to include this fix as its not useable without it.
https://github.com/RasPlex/OpenPHT/releases/tag/v1.8.0b

**Comment by anotherbob67** [comment]
I'm having the same issue as above.

**Comment by matthuisman** [comment]
sorry, i missed the first comment. ill have a look :)

**Comment by matthuisman** [comment]
1.8.0b now pushed. please test

**Comment by anotherbob67** [comment]
I can confirm current listing for RPi2 in Pinn installs a version of rasped which does not have the cert issue and is able to access libraries. 

Much joy!

**Comment by matthuisman** [comment]
yah. i also adding the Pi3B+ version for people using that board :)
