### ISSUE TITLE
Wrong repo url for Kano_OS in the json files for noobs

### ISSUE THREAD

**Issue by Wovchik** [matthuisman/pinn-os#3]
noob for RPI3 refer to:
"name" : "Matt Huisman",
"url"  : "http://raw.githubusercontent.com/matthuisman/pinn-os/master/os_list_v3.json"
in that file the urls are wrong.
they shoulkd be:
http://downloads.kano.me/public/noobs/link/...

**Comment by matthuisman** [comment]
Looks like they have changed the urls.
I'll update the os_list
